### ISSUE TITLE
gradle init

### ISSUE THREAD

**Issue by gadido30** [jorabin/KeePassJava2#21]
I tried to compile with gradle:

------------------------------------------------------------
Gradle 2.10
------------------------------------------------------------
Groovy:       2.4.5
Ant:          Apache Ant(TM) version 1.9.6 compiled on July 20 2018
JVM:          1.8.0_191 (Oracle Corporation 25.191-b12)
OS:           Linux 4.4.0-145-generic amd64

I got:

Caused by: org.codehaus.plexus.util.dag.CycleDetectedException: Edge between 'Vertex{label='org.apache.maven.plugin.MavenPluginManager:default'}' and 'Vertex{label='org.apache.maven.plugin.version.PluginVersionResolver:default'}' introduces to cycle in the graph org.apache.maven.plugin.version.PluginVersionResolver:default --> org.apache.maven.plugin.MavenPluginManager:default --> org.apache.maven.plugin.version.PluginVersionResolver:default
        at org.codehaus.plexus.util.dag.DAG.addEdge(DAG.java:143)
        at org.codehaus.plexus.util.dag.DAG.addEdge(DAG.java:123)
        at org.codehaus.plexus.component.composition.DefaultCompositionResolver.addComponentDescriptor(DefaultCompositionResolver.java:60)
        ... 79 more

any idea?
Thank You

**Comment by jorabin** [comment]
closing as this is now rather old and potentially not relevant any more
