### ISSUE TITLE
AspectJExpressionPointcut Exception with version 2.2.1 and higher

### ISSUE THREAD

**Issue by coli-21** [jorabin/KeePassJava2#73]
Hello!

In our Jakarta EE 10 environment (JDK 17, WebSphere Liberty 24.0.0.9, Spring 6.1.5, Maven ...), we have been using KeePassJava2 version 2.1.4. We now want to upgrade KeePassJava2 to version 2.2.1/2.2.2 because our users create kdbx databases with the KeePass Client 2.57.1, which apparently cannot be read with KeePassJava2 v2.1.4. However, when starting our WebSphere Liberty server, the following message is written to our server log multiple times. We already have dependencies on aspectjtools and spring-tx in the latest version.

`org.springframework.aop.aspectj.AspectJExpressionPointcut -- Failed to create fallback PointcutExpression
java.lang.IllegalArgumentException: error Type referred to is not an annotation type: org$springframework$transaction$annotation$Transactional
        at org.aspectj.weaver.tools.PointcutParser.parsePointcutExpression(PointcutParser.java:301)
        at org.springframework.aop.aspectj.AspectJExpressionPointcut.buildPointcutExpression(AspectJExpressionPointcut.java:223)
        at org.springframework.aop.aspectj.AspectJExpressionPointcut.getFallbackPointcutExpression(AspectJExpressionPointcut.java:400)
        at org.springframework.aop.aspectj.AspectJExpressionPointcut.getShadowMatch(AspectJExpressionPointcut.java:467)
        at org.springframework.aop.aspectj.AspectJExpressionPointcut.getTargetShadowMatch(AspectJExpressionPointcut.java:446)
        at org.springframework.aop.aspectj.AspectJExpressionPointcut.matches(AspectJExpressionPointcut.java:291)
        at org.springframework.aop.support.MethodMatchers.matches(MethodMatchers.java:111)
        at org.springframework.aop.support.MethodMatchers$IntersectionIntroductionAwareMethodMatcher.matches(MethodMatchers.java:350)
        at org.springframework.aop.support.AopUtils.canApply(AopUtils.java:258)
        at org.springframework.aop.support.AopUtils.canApply(AopUtils.java:295)
        at org.springframework.aop.support.AopUtils.findAdvisorsThatCanApply(AopUtils.java:327)
        at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findAdvisorsThatCanApply(AbstractAdvisorAutoProxyCreator.java:128)
        at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findEligibleAdvisors(AbstractAdvisorAutoProxyCreator.java:97)
        at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.getAdvicesAndAdvisorsForBean(AbstractAdvisorAutoProxyCreator.java:78)
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:366)
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:318)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:438)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.postProcessObjectFromFactoryBean(AbstractAutowireCapableBeanFactory.java:1907)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:139)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1819)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1276)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:259)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:365)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:135)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1685)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1434)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.resolveMethodArguments(AutowiredAnnotationBeanPostProcessor.java:887)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:848)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:145)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:508)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1419)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:784)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:767)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:145)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:508)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1419)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:962)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:394)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:274)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:102)
        at com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextCreated(WebApp.java:2464)
        at com.ibm.ws.webcontainer31.osgi.webapp.WebApp31.notifyServletContextCreated(WebApp31.java:512)
        at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:1062)
        at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:6722)
        at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost.startWebApp(DynamicVirtualHost.java:484)
        at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost.startWebApplication(DynamicVirtualHost.java:479)
        at com.ibm.ws.webcontainer.osgi.WebContainer.startWebApplication(WebContainer.java:1208)
        at com.ibm.ws.webcontainer.osgi.WebContainer.startModule(WebContainer.java:988)
        at com.ibm.ws.app.manager.module.internal.ModuleHandlerBase.deployModule(ModuleHandlerBase.java:101)
        at com.ibm.ws.app.manager.module.internal.DeployedModuleInfoImpl.installModule(DeployedModuleInfoImpl.java:51)
        at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.deployModules(SimpleDeployedAppInfoBase.java:600)
        at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:514)
        at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:625)
        at com.ibm.ws.app.manager.ear.internal.EARApplicationHandlerImpl.install(EARApplicationHandlerImpl.java:79)
        at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:199)
        at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1369)
        at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:912)
        at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:298)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:857)`

**Comment by jorabin-sense** [comment]
Hiya

I don't see anywhere in this stack trace that an error is being thrown by KeePassJava2 software, am I missing something? 

Could this be a configuration error unrelated to KeePassJava2?

thanks

**Comment by coli-21** [comment]
Hi jorabin,

thank you for your quick response! Unfortunately, I cannot rule out the possibility of a configuration error. The strange thing is that the error message appears as soon as KeePassJava2 is upgraded to version 2.2.1. I was hoping that one of the developers might have an immediate idea. Perhaps my issue would be better suited on stackoverflow.com?

**Comment by jorabin** [comment]
I have little experience with your environment, but it looks to me as though it's complaining about not being able to find an annotation type Transactional.

As a matter of interest, why are you using KeePassJava2 2.2.1 rather than 2.2.2? And fwiw 2.2.3 is on its way ... unless this Issue shows that there is something that could be fixed in that release ...

**Comment by coli-21** [comment]
Currently, we are using KeePassJava2 version 2.1.4 because we encountered the aforementioned error message with versions 2.2.1 and 2.2.2. 

To be able to build with Maven at all, we also had to explicitly name the following two artifacts

                    <exclude>org.codehaus.woodstox:stax2-api</exclude>
                    <exclude>com.fasterxml.woodstox:woodstox-core</exclude>

in the maven-enforcer-plugin, as there were complaints about different versions in the dependencies within pwdb:

`Dependency convergence error for org.codehaus.woodstox:stax2-api:jar:4.2 paths to dependency are:
        +-de.vw.cass:cass_api:war:3.6.0
          +-de.vw.cass:service:jar:3.6.0:compile
    +-org.linguafranca.pwdb:KeePassJava2:jar:2.2.2:compile
      +-org.linguafranca.pwdb:KeePassJava2-simple:jar:2.2.2:compile
        +-com.fasterxml:aalto-xml:jar:1.3.2:compile
          +-org.codehaus.woodstox:stax2-api:jar:4.2:compile
and
+-de.vw.cass:cass_api:war:3.6.0
          +-de.vw.cass:service:jar:3.6.0:compile
    +-org.linguafranca.pwdb:KeePassJava2:jar:2.2.2:compile
      +-org.linguafranca.pwdb:KeePassJava2-jackson:jar:2.2.2:compile
        +-com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.17.1:compile
          +-org.codehaus.woodstox:stax2-api:jar:4.2.2:compile`

**Comment by jorabin** [comment]
It looks like your maven dependency might be on the -all module, whereas you need to depend only on -jackson if that's the one you are using (recommended). So the question is which implementation are you using? Or to put it another way, when you load the database are you doing this:

`Database database = JacksonDatabase.load(credentials, inputStream)`

which is the recommended implementation going forward and will be the only one, soon.

And your Maven dependency would look like:

`<groupId>org.linguafranca.pwdb</groupId>
    <artifactId>KeePassJava2-jackson</artifactId>
    <version>2.2.2</version>`

to remove the conflict with simple. TBH I wasn't aware of the dependency mismatch but as mentioned elsewhere, the simple implementation is history so suggest you adjust your dependencies and the database load code and see where that gets you. 

It would be good to hear how you get on.

**Comment by jorabin** [comment]
Keen to hear of any change on this, otherwise will assume that the above suggestions worked for you and will close.

Thanks

**Comment by jorabin** [comment]
Hopefully the dependency mismatch has been corrected in 2.2.3 just released. So worth trying this again, or adopting the suggestion I made earlier.

**Comment by coli-21** [comment]
Hi Jorabin, thanks for your feedback! Sorry for my long absence (vacation, illness, have become parents .. :P). 

You guessed it right, when i load the database i am doing this:

`Database database = JacksonDatabase.load(credentials, inputStream)`

I tried to integrate **KeePassJava2-jackson** version 2.2.3, but I encountered the same issues as I mentioned on 24.11.24. 

When integrating KeePassJava2-jackson or KeePassJava2 (all) version 2.2.4-SNAPSHOT, I get a compilation error stating that the artifact org.linguafranca.pwdb:util:jar:2.2.4-SNAPSHOT cannot be found. When I check the repository via the browser, I indeed cannot find a 2.2.4-SNAPSHOT version of the Util module. Am I making a mistake in integrating it into Maven?

here is the detailed error message:
`
[ERROR] dependency: org.linguafranca.pwdb:util:jar:2.2.4-SNAPSHOT (compile)
ERROR] 	Could not find artifact org.linguafranca.pwdb:util:jar:2.2.4-SNAPSHOT in oss.sonatype.org-snapshot (https://oss.sonatype.org/content/repositories/snapshots)
`

**Comment by jorabin** [comment]
Hi @coli-21 sorry to hear about your illness, but delighted to hear that you have become parents! Congratulations!

So first of all you say you are excluding woodstox. That is the place where the conflict between simple and jackson is coming from, I think ... so you need to stop excluding it when you remove the dependency on Simple by having your Maven dependency on -jackson not -all. Forgive me for stating the obvious!

Secondly, to get hold of snapshot dependencies you need to add to your POM:

      <repositories>
         <repository>
           <id>oss.sonatype.org-snapshot</id>
           <url>https://oss.sonatype.org/content/repositories/snapshots</url>
           <releases>
             <enabled>false</enabled>
           </releases>
           <snapshots>
             <enabled>true</enabled>
           </snapshots>
         </repository>
       </repositories>

See [this test](https://github.com/jorabin/KeePassJava2Test/blob/master/V2.2.4/pom.xml) for an example.

Having dealt with the conflict, either by using -jackson dependency or by using 2.2.4-SNAPSHOT (or both, even) will remove KeePassJava2 as a cause of problems. As far as I can see from the stack trace the error is caused by inability to find https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/transaction/annotation/Transactional.html annotation. That's not part of KeePassJava2 which has no dependency on Spring at all. So if the error has started appearing then perhaps it's part of your application that has changed?

Also fwiw looks like you may be using autowiring, which I always felt was the cause of a few problems, and not the answer to many, as you could not be exactly sure what you ended up with in your application. However, strictly speaking that is none of my business - except if the error you are seeing is the result of accidental wiring of something not intended.

Congratulations again, hope you are getting plenty of sleep (!) and hope that all makes sense.
Jo

**Comment by jorabin** [comment]
Hi again @coli-21 I noticed just now that I had misread your earlier comment (more haste less speed) and hadn't realised that you know how to get the SNAPSHOT releases. Apologies for that. 

Your question is specifically not being able to find the `util` module but you don't need that at runtime, it's only used for tests, so is not deployed.

For avoidance of doubt the only KeePass dependency you need in your POM is 


		<dependency>
			<groupId>org.linguafranca.pwdb</groupId>
			<artifactId>KeePassJava2-jackson</artifactId>
			<version>2.2.4-SNAPSHOT</version>
		</dependency>

Hope that helps, let me know how you get on.
Jo

**Comment by jorabin** [comment]
Please close this issue if your problem is now solved, or if you don't need to solve it any more.

thanks

**Comment by jorabin** [comment]
I have released V 2.2.4 which I hope resolves this issue. Please re-open if required.

**Comment by jorabin** [comment]
@coli-21 Glad to hear that is sorted. Assume you are using 2.2.4?

While you are working on the code suggest that you look at 3.0.0-SNAPSHOT. I don't plan any further maintenance or upgrades on 2.2. So next time there is a KeePass file format change I would update 3.0 but I don't plan to update 2.2.

3.0 is simplified and easier to use than 2.2 - that said you'd need to do some refactoring to move from 2.2 to 3.0. See #62 and check out [this example](https://github.com/jorabin/KeePassJava2Test/blob/master/V3.0.0/src/main/java/org/linguafranca/pwdb/Issue80.java).

I'll do a release 3.0.0 at some point "soon"
